name: lda
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.20.3
  - curl
  - pip:
    - pygetwindow==0.0.9
    - colorama==0.4.6
    - rich==13.3.2
    - websockets==10.4
    - rembg==2.0.30
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - opencv-python-headless==4.1.2.30
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.7.6
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.7.0
    - kornia==0.6
    - accelerate==0.12.0
    - -e git+https://github.com/Astropulse/hitherdither#egg=hitherdither
    - -e git+https://github.com/CompVis/taming-transformers#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP#egg=clip
    - -e git+https://github.com/Astropulse/k-diffusion#egg=k_diffusion
    - -e .